apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-test
  name: httpd-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd-test
  template:
    metadata:
      labels:
        app: httpd-test
    spec:
      containers:
      - image: httpd:alpine3.18
        name: httpd
  strategy:
    type: Recreate
